name: 🏗️ Build Docker image for pull request

on:
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    name: 🐳 Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          # - linux/arm/v7
    steps:
      - name: 📥 Checkout the git repo
        uses: actions/checkout@v4

      - name: 🖥️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🏷️ Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: yogeshojha/rengine
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
            type=sha,prefix=sha-
            type=ref,event=branch
            type=ref,event=pr

      - name: 🏗️ Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: web/
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
